include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    file_names: ignore
    avoid_catches_without_on_clauses: ignore
  exclude: 
    - example/*

linter:
  rules:
    use_late_for_private_fields_and_variables: false
