name: any_date
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  meta: ^1.0.0

dev_dependencies:
  intl: ^0.18.0
  lints: ^2.0.0
  test: ^1.0.0
  very_good_analysis: ^5.0.0
